name: Testes Automatizados (CRUD Posts)

on: 
  push:
    branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "123456"
          MYSQL_DATABASE: microblogging_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalar Dependências
      run: npm install

    - name: Executar Testes
      run: npm run test